# Generated by Django 3.0.6 on 2020-05-29 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acceptance_number', models.CharField(max_length=20, unique=True)),
                ('acceptance_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('customer_phone', models.CharField(max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('down_payment', models.PositiveIntegerField(default=0)),
                ('residual', models.PositiveIntegerField(default=0)),
                ('is_washed', models.BooleanField(default=False)),
                ('is_taked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('sub_total', models.PositiveIntegerField(default=0)),
                ('acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_acceptances', to='acceptances.Acceptance')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_products', to='products.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
