# Generated by Django 3.0.6 on 2020-06-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptances', '0005_auto_20200602_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='status',
            field=models.CharField(choices=[('WASHED', 'Washed'), ('COMPLETED', 'Completed'), ('TAKED', 'Taked')], default='WASHED', max_length=10),
        ),
    ]
