# Generated by Django 3.0.6 on 2020-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profoss',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
